### ISSUE TITLE
Can´t open pjpysekai

### ISSUE THREAD

**Issue by DiegoBotto2004** [pjsek-ai/pypjsekai#36]
I have installed pypjsekai but how can I open it? I´ve been researching ways to open it but I can´t.

**Comment by erikchan002** [comment]
I will be adding some examples in the near future, but generally you can create a `Client` with the encryption keys and version hash and do most of the things with the `Client`

This module is annotated so you should be able to find your way through with type hints

**Comment by erikchan002** [comment]
Does the new examples in https://github.com/pjsek-ai/pypjsekai/tree/master/examples answer your question? @DiegoBotto2004

**Comment by DiegoBotto2004** [comment]
Yes, I suppose
